
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: portfolio_db
      POSTGRES_USER: pms_user
      POSTGRES_PASSWORD: PMS_DB_PS123
      POSTGRES_PORT: 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  backend:
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    # develop:
    #   watch:
    #     - action : sync+restart
    #       path : ./backend
    #       target: /app
    #       initial_sync: true
    #       ignore:
    #         - node_modules/
    #     - action: rebuild
    #       path: ./backend/package.json
    environment:
      - DEBUG=1

  celery:
    build: ./backend
    command: celery -A config worker -l info --pool=solo
    develop:
      watch:
        - action : sync+restart
          path : ./backend
          target: /app
          initial_sync: true
          ignore:
            - node_modules/
        - action: rebuild
          path: ./backend/package.json
    depends_on:
      - backend
      - redis

  celery_beat:
    build: ./backend
    command: celery -A config beat --loglevel=info
    # volumes:
    #   - ./backend:/app

    depends_on:
      - backend
      - redis

  frontend:
    command: npm run dev
    # volumes:
    #   - ./frontend:/app
    develop:
      watch:
        - action : sync
          path : ./frontend
          target: /app
          initial_sync: true
          ignore:
            - node_modules/
        - action: rebuild
          path: ./frontend/package.json
    environment:
      - DEBUG=1
      - API_BASE=http://backend:8000
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
      - NEXT_PUBLIC_API_VER_URL=/api/v1

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    ports:
      - "8080:80"

volumes:
  postgres_data:
